microsoft/qmt

README.md

Moving from travis-ci.com to travis-ci.org

Update travis link after switching the repository to public.

---

qmt/batchModel.py

Making current practice work for postprocessing.

Allow V as shortcut for voltage in genPhysicsSweep

---

qmt/freecad/geomUtils.py

Union would fail if it encountered  empty shapes. Added a check to see if shapes are empty and exclude them from the union.
Signed-off-by: John Gamble <johnkgamble@gmail.com>

Add nonEmpty check to union

---

qmt/batchHarness.py

When running under Windows, I found that the PATH environment variable is sometimes set to a unicode string, which subprocess.Popen does not accept for the env argument. This fix recodes all unicode entries.

Unicode changes to batchharness.py

---

qmt/freecad/objectConstruction.py
qmt/freecad/sketchUtils.py

If we have a sufficiently small offset, will now just return a copy of the original. This fixes some of the problems with SAG wire creation.
Signed-off-by: John Gamble <jgamble@basalt.guest.corp.microsoft.com>

Add fix for offsetting by a small value

---

qmt/batchModel.py

When evaluating stuff in parallel or doing something multiple times, my terminal gets spammed with 100s of copies of the following line:
```
Loading model file side_gates/geo_/model.json.
```
This PR removes that print statement and only prints a warning when the file cannot be opened.

print a warning when model cannot be opened, print nothing when succeeding

---

qmt/tasks/basic/geometry.py
qmt/tasks/basic/reduce_dim.py
qmt/tasks/sweep.py
qmt/tasks/task.py

Each Task has a _solve_instance method, which is pickled and passed between nodes by dask distributed. If this method is not static, the entire Task class gets pickled and passed between nodes, which leads to inefficiencies and unstable behavior.
In this PR, _solve_instance is made into a static method. This means that the _solve_instance method for each subTask class cannot take "self" as an argument.
Additionally the COMSOL mesh Task's "_solve_gather" method is also static, and is handed in an empty ReducedSweepResults object, instead of creating one inside the _solve_gather function.
Let me know if there are any issues with this!

_solve_instance method of tasks now a static method.

---

azure-pipelines.yml
tests/conftest.py

Andrey, do you remember why you included the --noconftest? It does exactly as advertised and leads to failing integration tests because pytest can't find the fixtures we define in conftest.py.

Fix py3 test pipeline: --noconftest prohibits pytest from finding fixtures

---

qmt/data/__init__.py
qmt/data/data_utils.py
qmt/tasks/geometry.py
tests/py3/test_geo_task.py

This update also changes the name of the serialization function. We add in the option to pass it directly to the build_3d_geometry so that Docker environments don’t need access to a shared drive. We also left the ability to automatically generate it, and added some sanity checks to avoid errors.

Add serial FreeCAD file passing to 3d geo build

---

qmt/data/geometry.py
qmt/geometry/freecad/objectConstruction.py
qmt/tasks/geometry.py
tests/py2.7/test_freecad_objectConstruction.py

This PR restores the ability to make cross sections from a 3D geometry. To avoid excessive calls to the wrapper, we specify these ahead of time at the time the geometry task is run. Note that the polygons returned don't know on their own how to define what is "inside" or "outside" of a domain. However, all of the relevant vertices should be there.

Make cross sections

---

deployment/environment_36.yml

Otherwise, dask schedulers won't start with the bokeh dashboard.

Add bokeh to the 3.6 environment

---

deployment/environment_36.yml

Also changed numpy to 1.13 for compatibility with fenics 2017.2. Using fenics in pip made it not able to import for some reason.

Move fenics back to conda

---

examples/deprecated/tasks_simple.py

Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.

Use print() function in both Python 2 and Python 3

---

qmt/geometry/property_map.py
qmt/materials.json
qmt/materials.py
tests/test_property_map.py

When properties of different parts had different types (e.g. int vs float) this could lead to randomly occurring truncations.
Also enforce uniform float type for material properties across different materials for consistency.

Fix property map bug

---

qmt/data/data_utils.py

Scratch read/write is needed to handle some serialization tasks. The default was to use the current directory, which causes problems for some NFS situations. Changing to use the system default temp location instead.

Improves handling of scratch directories

---

qmt/tasks/geometry.py

Right now, when an exception happens in `build`, the internal state isn't reset. Running the same (faulty) code cell again will result in a different error.
This fix ensures the correct cleanup.
We might also introduce our custom `contextmanager` to do this job.

always close the document

---

.gitattributes
qmt/__init__.py
qmt/_static_version.py
qmt/_version.py
setup.py

Currently, there is no way of finding out what version people have installed.
This makes sure that `qms.__version__` is always correctly defined, using [semver](https://semver.org/).
We would for example tag `1.1.0` now by doing:
```
git tag v1.1.0 -m "version 1.1.0"
```
It yields version strings like `1.1.0`, `1.1.0+2.g1076c97`, or `0.11+2.g1076c97.dirty`.
Where `1.1.0+2.g1076c97` means, 2 commits after the tag `1.1.0` and on the git hash 1076c97,
`dirty` means that there are unstaged files.

add miniver, get __version__ from git tags

---

qmt/data/data_utils.py
qmt/data/geometry.py
qmt/data/solvers_3d.py
qmt/geometry/freecad/auxiliary.py
qmt/geometry/freecad/fileIO.py
qmt/geometry/freecad/geomUtils.py
qmt/geometry/freecad/objectConstruction.py
qmt/geometry/freecad/sketchUtils.py
qmt/geometry/property_map.py
qmt/materials.py
qmt/physics_constants.py
qmt/tasks/geometry.py
tests/test_freecad_objectConstruction.py

Currently, the docstrings do not have any particular standard or style (to the best of my knowledge). 
I think the intention was to use standard Python reST style docstrings, however, they were not correct.
Besides that, those docstrings are very hard to read (and also hard to write). I propose to use NumPy style docstrings, which is the standard in almost all scientific packages.
~~Using this (a) standard, it is easy to create API documentation using Sphinx, see for example the documentation [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html#scipy.interpolate.interp1d) which is generated by this [source](https://github.com/scipy/scipy/blob/v1.2.1/scipy/interpolate/interpolate.py#L345-L701).~~
edit: I see that there is already documentation! And I …

convert reST docstring style to NumPy style

---

qmt/_version.py
qmt/geometry/freecad/objectConstruction.py
qmt/geometry/property_map.py
qmt/materials/materials.py
qmt/physics_constants.py

I just discovered `pyupgrade` which can convert the syntax to newly recommended ways of newer Python versions.

run pyupgrade --py36-plus

---

qmt/geometry/freecad/objectConstruction.py
qmt/geometry/part_3d.py

- Setting fc_name to None got broken during the refactor because I thought it would use label as the fc_name in that case. Apparently that's not the case, you'd have to do getObjectsByLabel first. This is now fixed
- More informative error message now if we're unable to find the 2d object to extrude/litho/etc

fix fc_name
