microsoft/qmt

qmt/freecad/fileIO.py, qmt/freecad/objectConstruction.py
Fixed geometry sweeps and verified that tests are passing.
=> Fix geom sweep

.travis.yml
FreeCAD 0.17 is the new stable version. Until we fix all incompatibilities we need to pull 0.16 from freecad-legacy.
=> Fix FreeCAD repo for travis

qmt/freecadMacros/pruneDXF.FCMacro
Previously, this macro would choke on splines and curves. This fixes that problem.
Signed-off-by: John Gamble <johnkgamble@gmail.com>
=> Revise pruneDXF FCMacro

qmt/batchHarness.py, qmt/batchModel.py, qmt/freecadMacros/pruneDXF.FCMacro
Port batch simulation support to our Azure Linux cluster.
=> Port to linux cluster

qmt/freecadMacros/pruneDXF.FCMacro
Makes sure that wires and edges are handled properly by the prune Macro
=> Prune changes

qmt/batchHarness.py
The solution files are now swept into an hdf5 file and then deleted.
=> Add data viz and automatic solution cleanup.

examples/1_3D_2DEG/makeRun.py, qmt/__init__.py, qmt/batchHarness.py, qmt/batchModel.py, qmt/freecad/fileIO.py, qmt/freecad/geomUtils.py, qmt/freecad/objectConstruction.py, qmt/freecad/sketchUtils.py, qmt/freecadMacros/etchParts.FCMacro, qmt/freecadMacros/pruneDXF.FCMacro, qmt/freecadMacros/sketchify.FCMacro, qmt/materials.py, qmt/physics_constants.py, setup.py, tests/test_batchHarness.py, tests/test_batchModel.py, tests/test_freecad_fileIO.py, tests/test_freecad_geomUtils.py, tests/test_freecad_objectConstruction.py, tests/test_freecad_sketchUtils.py, tests/test_materials.py, tests/test_units.py
This is just a small start :)
The Java style names still hurt my eyes but changing that will mean breaking compatibility.
=> Make a start to PEP8 compliant code

qmt/materials.py
=> generate the `materials.json` file as is reported in the print statement

azure-pipelines.yml
=> Azure pipelines improvements

doc/conf.py, examples/deprecated_visualization/density_1d_plot.py, examples/deprecated_visualization/density_2d_plot.py, examples/deprecated_visualization/mobility_plots.py, examples/deprecated_visualization/plot.py, examples/deprecated_visualization/plot_helpers.py, examples/meshing_sweep.py, examples/task_hello.py, examples/tasks_save_data.py, examples/tasks_sweep.py, setup.py, tests/py2.7/test_freecad_geomUtils.py, tests/py2.7/test_freecad_objectConstruction.py, tests/py2.7/test_freecad_sketchUtils.py, tests/py3/test_geo_task.py, tests/py3/test_tasks.py
=> Reformat code to conform to the PEP 8 style guide

qmt/materials.py
This update allows for a materials library to be modified with a new material object, and also for a material object to be updated with a new parameter. This is useful for customizing material parameters.
=> Add ability to modify materials

qmt/data/solvers_3d.py
Small change to add uniform_grid field in FEM3DData
=> Addition to FEM3DData class

azure-pipelines.yml
Switching our pipeline to a file
=> feat(azure): pipelines file

README.md, azure-pipelines.yml
New badge from updated pipeline
=> fix(readme): new badge

qmt/data/__init__.py, qmt/data/solvers_2d.py
=> added phase_data object

qmt/materials.json, qmt/materials.py
Set values of relative permittivity for metals to 1
=> Set relative permittivity metals to 1

qmt/geometry/freecad/objectConstruction.py, qmt/geometry/freecad_macros/add_params.FCMacro
Automatically generates a template spreadsheet for geometric parameters.
=> Add FCMacro for geometric parameters

Dockerfile, deployment/environment_full_linux.yml, deployment/environment_full_mac.yml
Minor change to add sudo in docker and descartes package to plot polygons in 2d
=> Environment update

README.md
* plus minor formatting proposals
=> Semantic issue on paragraph #10

deployment/environment_full_linux.yml, deployment/environment_min.yml
Adding deepdish, which is a HDF5 saving/loading library https://github.com/uchicago-cs/deepdish
Useful for phase diagram automation
=> fix(env): adding deepdish

deployment/environment_full_linux.yml, deployment/environment_min.yml
Adding nb_conda and jupyter_contrib_nbextensions, which makes working in a jupyter notebook easier
=> feat(env): adding jupyter tools

deployment/environment_full_mac.yml
Updating the mac env file since we added some packages
=> fix(env): updating mac env

examples/geometry_sweep/geometry_sweep.py
Updated geometry_sweep so it now works with current code.
- Changed the inputs to the build_3d_geometry function to match current version
- Removed Dask from example
=> Updated geometry_sweep example

qmt/data/geometry.py
Adding a method to geo2ddata for easy plotting
Mostly copied from @aeantipov 's notebook
=> fix(geo2ddata): plotting method

examples/geometry_sweep/geometry_sweep.py, qmt/data/geometry.py, qmt/geometry/freecad/fileIO.py, qmt/geometry/freecad/objectConstruction.py, tests/test_freecad_fileIO.py
Allows user to export 3D parts as .stl files.
=> Export .stl

examples/deprecated/tasks_simple.py, qmt/geometry/freecad/objectConstruction.py, qmt/geometry/property_map.py, qmt/materials.py, qmt/physics_constants.py, tests/test_freecad_fileIO.py, tests/test_freecad_geomUtils.py, tests/test_freecad_objectConstruction.py, tests/test_freecad_sketchUtils.py, tests/test_materials.py, tests/test_units.py
because we are Python 3 only now
=> remove 'six' dependency

qmt/data/geometry.py, qmt/geometry/freecad/fileIO.py, qmt/geometry/freecad/objectConstruction.py, qmt/geometry/freecad/sketchUtils.py
Asserts should be to catch bugs, not to raise mistakes of the user.
=> raise a KeyError instead of an assert

deployment/environment_full_linux.yml
See #115, [this](https://github.com/Microsoft/qmt/issues/115#issuecomment-485556375) comment.
=> fix matplotlib requirement

deployment/environment_full_linux.yml
This environment now works again, based on suggestion from https://github.com/conda-forge/matplotlib-feedstock/issues/206
=> fix(env): matplotlib

qmt/data/geometry.py
Fixes the projection so that the new axes are better aligned with the old axes
=> fix(geom): xsec_to_2d projection

qmt/data/geometry.py, qmt/data/solvers_3d.py
Needed in tandem with pull request adding volume disorder to qms.
=> Added disorder field to TransportData.

qmt/materials/mat_builder.py
virtual part does not need material
=> fix(build_materials): does not require material for

deployment/environment_min.yml
To make it more explicit what gets installed for which reason.
=> structure deployment/environment_min.yml

tests/conftest.py
This should solve the recent unpickling issue #134
=> Updated tf_data.pkl to solve unpickling issue

qmt/geometry/geo_2d_data.py
Fixes a bug in plot where it fails if the first part is a polygon
=> plotting polygon

examples/geometry_sweep/geometry_sweep.py
Make the geometry_sweep.py example compatible with new syntax.
@adamfrees
=> Update geometry sweep example

Dockerfile, README.md, azure-pipelines.yml, deployment/environment_full_linux.yml
=> fix environment

qmt/geometry/geo_2d_data.py, qmt/materials/mat_builder.py
Making mat_data work with 2d build
=> 2d materials

qmt/geometry/builder_3d.py, qmt/geometry/freecad/objectConstruction.py, qmt/geometry/geo_2d_data.py, qmt/geometry/geo_3d_data.py, qmt/geometry/geo_data_base.py, qmt/materials/mat_builder.py, tests/test_geo_objects.py
Adding a function to crop 2d geodata
=> fix(geo2ddatat): crop
